#ifndef CONFIG_H
#define CONFIG_H

// Arduino Mega 2560 핀 배치
#define RIGHT_SERVO_PIN 2
#define LEFT_SERVO_PIN 3
#define BUTTON_PIN 4
#define HEART_PIN 5
#define RIGHT_BRAKE_SCALE 0.98

// 무맥박 상태 및 심박 판정
#define NO_PULSE_BRAKING_TIME 2000UL
#define NO_PULSE_TIMEOUT 2000UL
#define NUM_BPM_READINGS 5

// 라이다 및 제동 파라미터
#define MAX_DECELERATION 15.0
#define SAFETY_MARGIN 150.0
#define MIN_SPEED_THRESHOLD 30.0
#define MIN_STRENGTH_THRESHOLD 1500
#define MAX_SPEED_NOISE 1000.0
#define REQUIRED_APPROACH_FRAMES 3
#define LONG_BRAKE_FRAMES 8
#define BRAKE_HOLD_TIME 1000UL
#define IMMEDIATE_BRAKE_HOLD_FRAMES 10

#endif
