#ifndef CONFIG_H
#define CONFIG_H

// Arduino Mega 2560 핀 배치
#define LEFT_SERVO_PIN 2
#define RIGHT_SERVO_PIN 3
#define BUTTON_PIN 4
#define HEART_PIN 5
#define RIGHT_BRAKE_SCALE 0.98
#define SERVO_MIN_ANGLE 0
#define SERVO_MAX_ANGLE 180
#define SERVO_ROUNDING_OFFSET 0.5
#define BRAKE_FULL_ANGLE SERVO_MIN_ANGLE
#define BRAKE_RELEASE_ANGLE SERVO_MAX_ANGLE
#define DEBUG_BAUD_RATE 115200UL

// 무맥박 상태 및 심박 판정
#define NO_PULSE_BRAKING_TIME 2000UL
#define NO_PULSE_TIMEOUT 2000UL
#define NUM_BPM_READINGS 5
#define HEART_SAMPLE_INTERVAL 10UL
#define MIN_VALID_IBI 300UL
#define MAX_VALID_IBI 2000UL
#define MILLISECONDS_PER_MINUTE 60000UL
#define CONTACT_LOST_BPM_THRESHOLD 140
#define CONTACT_LOST_SAMPLE_COUNT 4
#define INVALID_PULSE_LIMIT 8
#define NO_PULSE_BPM_THRESHOLD 40
#define TRIMMED_AVERAGE_COUNT 3

// 라이다 및 제동 파라미터
#define LIDAR_BAUD_RATE 115200UL
#define LIDAR_PACKET_SIZE 9
#define LIDAR_FRAME_HEADER 0x59
#define LIDAR_RESERVED_BYTES 3
#define LIDAR_MIN_DISTANCE 0
#define LIDAR_MAX_DISTANCE 800
#define LIDAR_SPEED_UPDATE_INTERVAL 100UL
#define MILLISECONDS_PER_SECOND 1000.0
#define MIN_SPEED_DT 0.001
#define INVALID_TTC 99.0
#define TTC_DISTANCE_LIMIT 400
#define MAX_DECELERATION 15.0
#define SAFETY_MARGIN 150.0
#define MIN_SPEED_THRESHOLD 30.0
#define MIN_STRENGTH_THRESHOLD 1500
#define MAX_SPEED_NOISE 1000.0
#define IMMEDIATE_BRAKE_DISTANCE 120
#define IMMEDIATE_BRAKE_TTC 1.0
#define FREE_ROLL_TTC_THRESHOLD 2.5
#define PROPORTIONAL_MIN_ANGLE 20
#define PROPORTIONAL_MAX_ANGLE 140
#define REQUIRED_APPROACH_FRAMES 3
#define LONG_BRAKE_FRAMES 8
#define BRAKE_HOLD_TIME 1000UL
#define IMMEDIATE_BRAKE_HOLD_FRAMES 10
#define BRAKE_CONTROL_INTERVAL 100UL
#define TELEMETRY_INTERVAL 250UL
#define BRAKE_PERCENT_MAX 100

#endif
